version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    image: surya-app:latest
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE_DOCKER}
      - DB_DRIVER=${DB_DRIVER}
      - SERVER_ADDRESS=0.0.0.0:8080
      - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
      - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
      - ACCESS_TOKEN_EXPIRED_IN=${ACCESS_TOKEN_EXPIRED_IN}
      - ACCESS_TOKEN_MAXAGE=${ACCESS_TOKEN_MAXAGE}
      - REFRESH_TOKEN_PRIVATE_KEY=${REFRESH_TOKEN_PRIVATE_KEY}
      - REFRESH_TOKEN_PUBLIC_KEY=${REFRESH_TOKEN_PUBLIC_KEY}
      - REFRESH_TOKEN_EXPIRED_IN=${REFRESH_TOKEN_EXPIRED_IN}
      - REFRESH_TOKEN_MAXAGE=${REFRESH_TOKEN_MAXAGE}
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: ["/app/main"]

volumes:
  postgres: