version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB=surya_app
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE_DOCKER}
      # - DB_DRIVER=postgres
      # - SERVER_ADDRESS=0.0.0.0:8080

      # - ACCESS_TOKEN_PRIVATE_KEY=${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
      # - ACCESS_TOKEN_PUBLIC_KEY=${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}
      # - ACCESS_TOKEN_EXPIRED_IN=1m
      # - ACCESS_TOKEN_MAXAGE=1

      # - REFRESH_TOKEN_PRIVATE_KEY=${{ secrets.REFRESH_TOKEN_PRIVATE_KEY }}
      # - REFRESH_TOKEN_PUBLIC_KEY=${{ secrets.REFRESH_TOKEN_PUBLIC_KEY }}
      # - REFRESH_TOKEN_EXPIRED_IN=60m
      # - REFRESH_TOKEN_MAXAGE=60
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: ["/app/main"]

volumes:
  pgdata: