// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type Company struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	Owner   int64  `json:"owner"`
}

type Report struct {
	ID        int64     `json:"id"`
	Date      time.Time `json:"date"`
	Outlet    string    `json:"outlet"`
	Item      string    `json:"item"`
	Problem   string    `json:"problem"`
	Status    string    `json:"status"`
	Remark    string    `json:"remark"`
	Owner     int64     `json:"owner"`
	CompanyID int64     `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Fullname  string    `json:"fullname"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
