name: Deploy docker images

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v3

    - name: Get Tag Name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build container image
      run: docker build -t registry.digitalocean.com/surya-registry/surya-app:${{ env.RELEASE_VERSION }} .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/surya-registry/surya-app:${{ env.RELEASE_VERSION }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ./surya-app-api/
          docker compose down
          docker rmi surya-app-api
          docker pull registry.digitalocean.com/surya-registry/surya-app:${{ env.RELEASE_VERSION }}
          docker tag registry.digitalocean.com/surya-registry/surya-app:${{ env.RELEASE_VERSION }} surya-app-api
          docker compose --env-file .env up -d